language: android
sudo: false
jdk: oraclejdk7
android:
    components:
        - build-tools-22.0.1
        - android-22
        - platform-tools
        - extra-android-support
        - extra-android-m2repository
    licenses:
        - 'android-sdk-license-.+'
script:
    - ./gradlew clean build